### ISSUE TITLE
Tutorial for how to set up endpoint

### ISSUE THREAD

**Issue by W1GZY** [zodaz/star-calling-assist#1]
This is probably very noob question but I am wondering if there is a simple tutorial to create the location for endpoint for us mortals that wants to use this plugin

**Comment by W1GZY** [comment]
Any updates here yet?

**Comment by zodaz** [comment]
> This is probably very noob question but I am wondering if there is a simple tutorial to create the location for endpoint for us mortals that wants to use this plugin

I completely forgot to reply to this, sorry. There is not a tutorial for setting up an endpoint to work with the plugin, and other than supplying the format in which calls are being sent (README.md), it's unfortunately not something I'm able to help you with.

**Comment by hwhmeikle** [comment]
I've made a server that integrates with this plugin, check out my repo https://github.com/KPSmartest/discord-shooting-star-caller
