### ISSUE TITLE
Valid Key Invalidates Within Minutes

### ISSUE THREAD

**Issue by oniryuuko** [zodaz/star-calling-assist#8]
Generate a valid key, put it into the plugin, get a list of stars, and within minutes I get the message 'Error fetching list of stars: Invalid key. Go to [link] to generate a valid key.' So I do so, and the problem repeats immediately. Curiously, while failing to get a list of stars, it still has no problem uploading info about stars, as I receive messages about 'Successfully posted call...'

**Comment by zodaz** [comment]
> Generate a valid key, put it into the plugin, get a list of stars, and within minutes I get the message 'Error fetching list of stars: Invalid key. Go to [link] to generate a valid key.' So I do so, and the problem repeats immediately. Curiously, while failing to get a list of stars, it still has no problem uploading info about stars, as I receive messages about 'Successfully posted call...'

It sounds like you might be leaving the discord server after receiving your key, that would cause your key to be invalidated.
At the moment, the key is only enforced on upload during periods when we see bad actors trying to fill the list with false information.
